version: '3.8'

services:
  db:
    container_name: exchangedb
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchangedb
      - POSTGRES_USER=sa_exchange
      - POSTGRES_PASSWORD=exchangedb@123
      - POSTGRES_PORT=5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - inspetor_network

volumes:
  postgres-data:
networks:
  inspetor_network:
    name: exchange