version: '3.8'

services:
  db:
    container_name: exchangedb
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchangedb
      - POSTGRES_USER=sa_exchange
      - POSTGRES_PASSWORD=exchangedb@123
      - POSTGRES_PORT=5432
    networks:
      - inspetor_network

networks:
  inspetor_network:
    name: exchange